config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'regions/index'
  
  resources :students
  resources :courses
  resources :states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :training_plan
  belongs_to :region
  
  has_many :students

end

app/models/region.rb
class Region < ApplicationRecord
    has_many :courses
    has_many :students

end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
  has_many :students
  
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :region
  belongs_to :course

end

app/models/training_plan.rb
class TrainingPlan < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @students = Student.all
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:start_date, :end_date, :training_plan_id, :region_id)
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  def index
    @regions = Region.all
  end

  def show
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name, :region_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(:distinct => true).includes(:course, :region)
    @courses = Course.all
    @regions = Region.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:rut, :name, :last_name1, :last_name2, :address, :region_id, :course_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Start date:</strong>
    <%= course.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= course.end_date %>
  </p>

  <p>
    <strong>Training plan:</strong>
    <%= course.training_plan_id %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= course.region_id %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :training_plan_id, style: "display: block" %>
    <%= form.text_field :training_plan_id %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<div class="container text-center">
  
  <h1 class="text-center">Cursos</h1>
  
  <table class="table table-bordered border-dark">
      <thead>
          <tr class="inline-block">
              <th>ID Curso</th>
              <th>Fecha Inicio</th>
              <th>Fecha Término</th>
              <th>Region</th>
              <th>Detalles</th>
          </tr>
      </thead>
      <tbody>
          <% @courses.each do |course| %>
              <tr>
                  <td><%= course.code %></td>
                  <td><%= course.start_date %></td>
                  <td><%= course.end_date %></td>
                  <td><%= course.region.name %></td>
                  <td class="d-flex justify-content-evenly">
                  <%= link_to "Ver", course, class:"btn btn-dark"%>
                  </td>
              </tr>
          <% end %>
      </tbody>
  </table>
  
  <%= link_to "New course", new_course_path, class:"btn btn-dark mb-3" %>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Examen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="/">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#"></a>
          <p> <%= image_tag "logo-red", class:"navbar-image mt-3" %> </p>
          <p> <%= image_tag "title-white", class:"navbar-title mt-3" %> </p>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
              <a class="nav-link active" aria-current="page" href="/courses">Cursos</a>
              <a class="nav-link active" href="/students">Estudiantes</a>
              <a class="nav-link active" href="/regions/index">Regiones</a>
            </div>
          </div>
        </div>
      </nav>
    </div>

    <div class="container"><%= yield %>  </div>
    
  <footer class="foo bg-dark text-center">
    <%= image_tag "logo-all", class:"logo-footer" %>
  </footer>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  </body>
</html>

app/views/regions/index.html.erb
<div class="container text-center">

    <h1 class="text-center">Regiones</h1>

    <table class="table table-bordered border-dark">
        <thead>
            <tr class="inline-block">
                <th>ID Region</th>
                <th>Nombre</th>
            </tr>
        </thead>
        <tbody>
            <% @regions.each do |region| %>
                <tr>
                    <td><%= region.id %></td>
                    <td><%= region.name %></td>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Name:</strong>
    <%= state.name %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= state.region_id %>
  </p>

</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>States</h1>

<div id="states">
  <% @states.each do |state| %>
    <%= render state %>
    <p>
      <%= link_to "Show this state", state %>
    </p>
  <% end %>
</div>

<%= link_to "New state", new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name1, style: "display: block" %>
    <%= form.text_field :last_name1 %>
  </div>

  <div>
    <%= form.label :last_name2, style: "display: block" %>
    <%= form.text_field :last_name2 %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Rut:</strong>
    <%= student.rut %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Last name1:</strong>
    <%= student.last_name1 %>
  </p>

  <p>
    <strong>Last name2:</strong>
    <%= student.last_name2 %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= student.region_id %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= student.course_id %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<div class="container text-center">
<h1 class="mt-5 mb-5">Estudiantes</h1>

<div class="container">
    <%= search_form_for @q do |f| %>
    <div class="d-flex align-items-center bg-white rounded-top p-3">
    <div class="col-3 me-3">
        <%= f.label :region_name_cont, 'Region', :class => 'form-label' %>
        <%= f.select :region_name_cont, options_for_select(@regions.map { |r| [r.name]}), {:include_blank => "Elige una region"}, {:class => 'form-select'} %>
        </div>
        <div class="col-3">
        <%= f.label :course_code_eq, "Curso", :class => 'form-label' %>
        <%= f.select :course_code_eq, options_for_select(@courses.map { |c| [c.code]}), {:include_blank => "Elige un curso"}, {:class => 'form-select'} %>
        </div>
        <div class="ms-3 align-self-end">
        <%= f.submit "Filtrar", {:class => 'btn btn-dark'} %>
        </div>
    </div>
    <% end %>
</div>


    <table class="table table-bordered border-dark">
        <thead>
            <tr class="inline-block ">
                <th>ID Estudiante</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Region</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <% @students.each do |student| %>
                <tr>
                    <td><%= student.id %></td>
                    <td><%= student.name %></td>
                    <td><%= student.address %></td>
                    <td><%= student.region_id %></td>
                    <td class="d-flex justify-content-evenly">
                    <%= link_to "Ver", student, class:"btn btn-dark"%>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to "New student", new_student_path, class: "btn btn-dark mb-3" %>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @student %>">
  <p>
    <strong>Rut:</strong>
    <%= @student.rut %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= @student.name %>
  </p>

  <p>
    <strong>Apellido Paterno:</strong>
    <%= @student.last_name1 %>
  </p>

  <p>
    <strong>Apellido Materno:</strong>
    <%= @student.last_name2 %>
  </p>

  <p>
    <strong>Dirección:</strong>
    <%= @student.address %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @student.region_id %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= @student.course_id %>
  </p>

   <p>
    <strong>Fecha Inicio:</strong>
    <%=@student.course.start_date %>
  </p>

  <p>
    <strong>Fecha Término:</strong>
    <%= @student.course.end_date %>
  </p>



</div>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>